resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github
      name: florimondmanca/azure-pipelines-templates
      ref: refs/tags/3.2

trigger:
  - master
  - refs/tags/*

pr:
  - master

variables:
  CI: true
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.cache/pip

stages:
  - stage: test
    jobs:
      - template: job--python-check.yml@templates
        parameters:
          pythonVersion: "3.8"
      - template: job--python-test.yml@templates
        parameters:
          jobs:
            py36:
            py37:
            py38:
              coverage: true

  - stage: publish
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
      - template: job--python-publish.yml@templates
        parameters:
          pypiRemote: pypi-public
